version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: nextjsdb
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d nextjsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  nextjs:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/nextjsdb
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

networks:
  app_network:
    driver: bridge
